<?php

namespace Magenest\MitoPayment\Block;

use Magento\Framework\Phrase;
use Magento\Payment\Block\ConfigurableInfo;

/**
 * Class Info
 *
 * @package DrinkiesLocal\MomoPay\Block
 */
class Info extends ConfigurableInfo
{
    /**
     * @param string $field
     * @return Phrase|string
     */
    protected function getLabel($field)
    {
        switch ($field) {
            case 'requestId':
                return __('Request Id');
            case 'orderType':
                return __('Order Type');
            case 'transId':
                return __('Trans Id');
            case 'message':
                return __('Message');
            case 'localMessage':
                return __('Local Message');
            case 'responseTime':
                return __('Response Time');
            case 'errorCode':
                return __('Error Code');
            case 'payType':
                return __('Pay Type');
            case 'extraData':
                return __('Extra Data');
            default:
                return parent::getLabel($field);
        }
    }

    /**
     * @param string $field
     * @param string $value
     * @return Phrase|string
     */
    protected function getValueView($field, $value)
    {
        return parent::getValueView($field, $value); // TODO: Change the autogenerated stub
    }
}
